"""Initial migration

Revision ID: b0ffc569636c
Revises: 
Create Date: 2025-04-29 07:17:51.966445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0ffc569636c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('hotel_images')
    op.drop_table('users')
    op.drop_table('room_images')
    op.drop_table('reviews')
    op.drop_table('payment')
    op.drop_table('services')
    op.drop_table('hotels')
    op.drop_table('rooms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('room_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_type', mysql.VARCHAR(length=35), nullable=True),
    sa.Column('availableRooms', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('hotel_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.hotel_id'], name='rooms_ibfk_1'),
    sa.PrimaryKeyConstraint('room_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('hotels',
    sa.Column('hotel_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hotel_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('address_hotel', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('tel', mysql.VARCHAR(length=13), nullable=True),
    sa.Column('rating', mysql.FLOAT(), nullable=True),
    sa.Column('descriptions', mysql.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('hotel_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('services',
    sa.Column('id_service', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('serviceName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('room_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name='services_ibfk_1'),
    sa.PrimaryKeyConstraint('id_service'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payment',
    sa.Column('payment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payment_status', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('payment_method', mysql.ENUM('vnpay', 'momo'), nullable=True),
    sa.Column('amount', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('booking_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name='payment_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='payment_ibfk_1'),
    sa.PrimaryKeyConstraint('payment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reviews',
    sa.Column('review_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', mysql.FLOAT(), nullable=True),
    sa.Column('comment', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('hotel_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.hotel_id'], name='reviews_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='reviews_ibfk_1'),
    sa.PrimaryKeyConstraint('review_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('room_images',
    sa.Column('image_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_path', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('is_main', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name='room_images_ibfk_1'),
    sa.PrimaryKeyConstraint('image_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('full_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('hotel_images',
    sa.Column('image_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_path', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('is_main', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.hotel_id'], name='hotel_images_ibfk_1'),
    sa.PrimaryKeyConstraint('image_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bookings',
    sa.Column('booking_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('room_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('check_in', mysql.DATETIME(), nullable=True),
    sa.Column('check_out', mysql.DATETIME(), nullable=True),
    sa.Column('total_price', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], name='bookings_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='bookings_ibfk_1'),
    sa.PrimaryKeyConstraint('booking_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
